### ISSUE TITLE
cannot import vuls scan result in ES

### ISSUE THREAD

**Issue by mareban** [usiusi360/vuls-log-converter#9]
Hello,

i've upgrade vuls to the last version yerderday, install vuls-log-convert, and i'm not able to convert the  result into csv or json !!!

I've tried the patch from snyk too, and same error !!

do i miss something, is it a bug, or an incompatibilities ??

Hereis the error message  :  

[INFO] : Convert start.
TypeError: Cannot convert undefined or null to object
    at getFlatObj (/var/bel/vuls/vuls-log-converter/vuls-log-converter-snyk-fix-6cd0eb2f/bin/vuls-log-converter.js:102:16)
    at /var/bel/vuls/vuls-log-converter/vuls-log-converter-snyk-fix-6cd0eb2f/bin/vuls-log-converter.js:612:24
    at Array.forEach (native)
    at /var/bel/vuls/vuls-log-converter/vuls-log-converter-snyk-fix-6cd0eb2f/bin/vuls-log-converter.js:610:18

Thanks for your help.

**Comment by aderumier** [comment]
Hi,
I have work on it,
can you test:

https://github.com/usiusi360/vuls-log-converter/pull/10

?

(I have only tested export to csv for now, seem to works fine)

**Comment by mareban** [comment]
Hello,

Thanks a lot, i can import the results in ES 7.x now :-) !

Thx

**Comment by mareban** [comment]
Happy new year !

I don't know if the project is still maintained, but we've upgraded vuls to the latest version, but still using ES 7.6.1, and this is the message we've got :-( : 

TypeError: Cannot read property 'replace' of undefined                                                                
    at getSplitArray (/usr/local/lib/node_modules/vuls-log-converter/bin/vuls-log-converter.js:374:24)                
    at getCvss (/usr/local/lib/node_modules/vuls-log-converter/bin/vuls-log-converter.js:258:43)                      
    at /usr/local/lib/node_modules/vuls-log-converter/bin/vuls-log-converter.js:279:33                                
    at Array.forEach (<anonymous>)                                                                                    
    at /usr/local/lib/node_modules/vuls-log-converter/bin/vuls-log-converter.js:277:29                                
    at Function.each (/usr/local/lib/node_modules/vuls-log-converter/node_modules/underscore/underscore-umd.js:1330:9)
    at /usr/local/lib/node_modules/vuls-log-converter/bin/vuls-log-converter.js:157:16                                
    at Function.each (/usr/local/lib/node_modules/vuls-log-converter/node_modules/underscore/underscore-umd.js:1335:9)
    at getFlatObj (/usr/local/lib/node_modules/vuls-log-converter/bin/vuls-log-converter.js:149:12)                   
    at /usr/local/lib/node_modules/vuls-log-converter/bin/vuls-log-converter.js:613:24

So, i guess vulslogconverter is not compatible with the new version of vuls ?


Thanks for your help
